language: php
sudo: false

php:
    - nightly
    - '7.1'
    - '7.0'
    - '5.6'
    - '5.5'
    - '5.4'
    - '5.3'
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
    - travis_retry composer install --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit --coverage-text
